### ISSUE TITLE
Implement a system to mark downloads as failed if errors occur, with descriptive error messages to aid in troubleshooting.

### ISSUE THREAD

**Issue by TimPietrusky** [blib-la/captain#131]
### User Story

**Title**: Handle Failed Downloads with Descriptive Error Messages

**As a** user of Captain,

**I want** the system to mark downloads as failed and provide descriptive error messages if errors occur,

**So that** I can understand why a download failed and attempt to troubleshoot or retry the download.

### Acceptance Criteria (Behavior Outline)

```cucumber
Feature: Handling Failed Downloads

  Scenario: Download fails due to an error
    Given the user initiates a download
    When the download fails due to an error
    Then the download is marked as "Failed"
    And a descriptive error message is displayed to the user

  Scenario: User views details of a failed download
    Given a download has failed
    When the user selects the failed download
    Then the system displays detailed error information including possible causes and troubleshooting steps

  Scenario: Retrying a failed download
    Given a download has failed
    When the user opts to retry the download
    Then the system attempts to restart the download process

  Scenario: User receives suggestions for troubleshooting
    Given a download has failed
    When the user views the error message
    Then the system provides suggestions for troubleshooting based on the type of error encountered
```

###  Subtasks

- [x] Design UI components for displaying failed downloads with "Failed" status indicators.
- [ ] Develop functionality for users to easily retry failed downloads.
- [ ] Integrate error logging for failed downloads to aid in further development and troubleshooting.
