### ISSUE TITLE
Generate Images from a text prompt with stable diffusion

### ISSUE THREAD

**Issue by pixelass** [blib-la/captain#190]
### User Story

**Title**: Generate Images from a Text Prompt with Stable Diffusion

**As a** user of Captain,

**I want** to create images from text prompts using Stable Diffusion,

**So that** I can easily generate visuals based on my textual input within the app.

### Acceptance Criteria (Behavior Outline)

```cucumber
Feature: Image Generation with Text Prompts

  Scenario: User inputs a text prompt for image generation
    Given the user has access to a text to image app within Captain
    When the user inputs a text prompt
    Then the app uses Stable Diffusion to generate an image corresponding to the prompt

  Scenario: Viewing generated images
    Given a user has generated an image with a text prompt
    When the image generation process is complete
    Then the generated image is displayed to the user within the app

  Scenario: Accessing and managing generated images
    Given a user has generated one or more images
    When the user wants to view or manage their generated images
    Then the user can access a gallery or inventory of their generated images within Captain
```

### SubTasks

- [ ] **Create a Simple Text to Image App**: Design and develop a user interface within Captain for users to input text prompts and view generated images.
- [ ] **Provide a Backend for Text to Image Operations**: Set up backend services that process text prompts using Stable Diffusion models to generate images.
- [ ] **Ensure Required Models Are Available**: Integrate and manage Stable Diffusion models, ensuring they are updated and accessible for image generation operations.
